apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  namespace: nvg-cdp
spec:
  replicas: 1
  selector:
    matchLabels:
      component: customers
  template:
    metadata:
      labels:
        component: customers
    spec:
      imagePullSecrets:
        - name: us-icr-io
      containers:
        - name: customer
          image: us.icr.io/naveggcdp/cdp-customers
          ports:
            - containerPort: 42078
          env:
            - name: KAFKA_BROKERS
              value: 'my-cluster-kafka-bootstrap:9092,my-cluster-kafka-bootstrap:9092,my-cluster-kafka-bootstrap:9093'
            - name: MONGO_URI
              value: 'mongodb://customers-mongo-cluster-ip-service:27017/customers'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secretjwt
                  key: SECRET_JWT