apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-mongo-deployment
  namespace: nvg-cdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-mongo
  template:
    metadata:
      labels:
        app: customers-mongo
    spec:
      containers:
        - name: customers-mongo
          image: mongo
          imagePullPolicy: IfNotPresent
          volumeMounts:
              - name: customers-mongo-storage
                mountPath: /data/db
      volumes:
        - name: customers-mongo-storage
          persistentVolumeClaim:
            claimName: customers-mongo-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: customers-mongo-cluster-ip-service
  namespace: nvg-cdp
spec:
  selector:
    app: customers-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customers-mongo-persistent-volume-claim
  namespace: nvg-cdp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi